packages:
  - packages/*
  - apps/*
  - '!apps/browser-proxy'
allowBuilds:
  esbuild: true
  protobufjs: true
  better-sqlite3: true
  sharp: true
minimumReleaseAgeExclude:
  - tsx@4.23.5
  - mysql2@3.24.1
  - '@vitejs/plugin-react@6.1.1'
